[project]
name = "weather-widget"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "openmeteo-requests>=1.7.2",
    "requests-cache>=1.2.1",
    "retry-requests>=2.0.0",
]
